"""add last_context_reset_at field to chats table

Revision ID: 9a7494d2cf40
Revises: 4fe63ece90f3
Create Date: 2025-06-06 21:26:31.493215

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a7494d2cf40'
down_revision: Union[str, None] = '4fe63ece90f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('last_context_reset_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_column('chats', 'last_context_reset_at')
    # ### end Alembic commands ###
