"""add creator id to apps table

Revision ID: 9b62dce48f00
Revises: a9d38b8833ce
Create Date: 2025-05-23 17:00:34.979090

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b62dce48f00'
down_revision: Union[str, None] = 'a9d38b8833ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('creator_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'applications', 'users', ['creator_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'applications', type_='foreignkey')
    op.drop_column('applications', 'creator_id')
    # ### end Alembic commands ###
