"""replace email postfix with auth provider name

Revision ID: a9d38b8833ce
Revises: 955724ff6d19
Create Date: 2025-05-23 16:00:48.914731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9d38b8833ce'
down_revision: Union[str, None] = '955724ff6d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('auth_provider_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'applications', ['auth_provider_name'])
    op.drop_column('applications', 'email_postfix')
    op.drop_constraint('messages_chat_id_fkey', 'messages', type_='foreignkey')
    op.create_foreign_key(None, 'messages', 'chats', ['chat_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.create_foreign_key('messages_chat_id_fkey', 'messages', 'chats', ['chat_id'], ['id'], ondelete='CASCADE')
    op.add_column('applications', sa.Column('email_postfix', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'applications', type_='unique')
    op.drop_column('applications', 'auth_provider_name')
    # ### end Alembic commands ###
